default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>


development:
  <<: *default
  database: blogproject_development

test:
  <<: *default
  database: blogproject_test

production:
  <<: *default
  database: blogproject_production
  url: <%= ENV['DATABASE_URL'] %>

