# config/webpacker.yml

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Uncomment the following lines to turn webpacker compression ON
  # production:
  #   compression: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  # resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  # cache_manifest: false

  # Extract and emit a css file
  # extract_css: false

  # Add entry configuration
  entry:
    application:
      - 'application.js'

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  # Check is not performed when running bin/rails webpacker:install for compatibility reasons
  # Uncomment the following lines to turn webpacker checks ON
  # check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    # webpack: { resolve: { alias: { '@': 'app/javascript' } } }

test:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    # webpack: { resolve: { alias: { '@': 'app/javascript' } } }

production:
  <<: *default
  compile: true
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  # cache_manifest: true

  # Extract and emit a css file
  # extract_css: true


